# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - name: Setup & Build
    init: pnpm install
    command: pnpm nr build --watch
    vscode:
      extensions:
          - amodio.tsl-problem-matcher